apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-nginx.fullname" . }}
  labels:
    {{- include "my-nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-nginx.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "my-nginx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP              
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: nginx-data
            mountPath: /usr/share/nginx/html/test
          - name: nginx-server-block-paths
              mountPath: /opt/bitnami/nginx/conf/server_blocks
            {{- if or .Values.serverBlock .Values.existingServerBlockConfigmap }}
          - name: nginx-server-block
              mountPath: /opt/bitnami/nginx/conf/server_blocks/common
            {{- end }}  
      volumes:
      - name: nginx-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "my-nginx.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: nginx-server-block-paths
          configMap:
            name: {{ template "my-nginx.fullname" . }}-server-block
            items:
              - key: server-blocks-paths.conf
                path: server-blocks-paths.conf
        {{- if or .Values.serverBlock .Values.existingServerBlockConfigmap }}
      - name: nginx-server-block
          configMap:
            name: {{ include "nginx.serverBlockConfigmapName" . }}
            {{- if or .Values.serverBlock }}
            items:
              - key: server-block.conf
                path: server-block.conf
            {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
